### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by Frozel** [Cloudwhale/vk-bot2#1]
Приветствую, а можно, пожалуйста, подробный гайд по запуску на убунту 16.04

root@instance-12:/usr/share/go/src/github.com/cloudwhale/vk-bot2# go run main.go
Error :(
%s open /usr/share/go/src/github.com/cloudwhale/vk-bot2\botconfig.ini: no such file or directory
Не найден конфигурационный файл, \botconfig.ini :(
exit status 1

**Comment by Cloudwhale** [comment]
Здравствуйте, этот бот пока что только для платформы Windows.

**Comment by Frozel** [comment]
Не принципиально:)

**Comment by Cloudwhale** [comment]
Извините, но random_photo работает только с альбомом "Сохраненные фотографии". Возможно он у вас закрыт :).

**Comment by Frozel** [comment]
Да, он был пуст, щас сохранил туда фотографии и.. какой ид указывать? Я пробовал *id страницы_000*, просто id страницы, просто 000

**Comment by Cloudwhale** [comment]
Id страницы, с которой вы будете очищать список. Напомню, что бот игнорирует сообщения, отправленные с его страницы.

**Comment by Frozel** [comment]
Ну насколько я понял...
token = здесь у меня прописан токен паблика в сообщениях которого бот отвечает
time  = 017-02-10 23:01:41.7896808 0200 EET
admin_id  =  здесь прописан ид моей вк страницы
album_id  =  здесь всё так же прописывать ид вк страницы при желании(?)
group_id  =  здесь ид паблика

бот работает и отвечает, но вот с фото и аудио разобраться не получается..

**Comment by Cloudwhale** [comment]
Перейдите в ваш альбом и из урл'а скопируйте число после ```_```. Это и есть album_id.
Прошу прощения, если что-то будет работать не так, как задумано, не запускал бота в группах.

**Comment by Frozel** [comment]
Id альбома сохраненных фотографий всегда 000; idстраницы_000

**Comment by Cloudwhale** [comment]
Для загрузка изображений вам необходимо создать еще один альбом и указать его id в album_id.
Id пользователя не имеет ```_```. Для удобства используйте сервис: http://showid.ru/

**Comment by Frozel** [comment]
token = здесь у меня прописан токен паблика в сообщениях которого бот отвечает
time = 017-02-10 23:01:41.7896808 0200 EET
admin_id = здесь прописан ид моей вк страницы
album_id = прописал id нового альбома сохранив при этом туда фотографии
group_id = здесь ид паблика

остальные поля не изменял

всё равно на запрос randomphoto отвечает, что альбом пуст

**Comment by Cloudwhale** [comment]
К сожалению эти методы недоступны для групп. На [этой](https://vk.com/dev/bizmessages_doc?f=2.1) странице написаны поддерживаемые методы.

**Comment by Cloudwhale** [comment]
Если я правильно понял, то вам нужен еще один аккаунт, чтобы получить его токен, отправить фотографию в его альбом и с помощью ключа сообщества отправить фотографию в диалог.

**Comment by Frozel** [comment]
Аккаунт есть, вопрос только куда его потом вписать для бота, если в конфиге используется токен паблика?

**Comment by Cloudwhale** [comment]
Замените токен пользователя на ключ сообщества при отправке сообщений(send.go). Все остальные действия делайте с токеном.

**Comment by Frozel** [comment]
В конфиге прописан токен сообщества, не понял, что изменить в send.go

**Comment by Cloudwhale** [comment]
в директории modules есть функция Request. Напишите свою функцию отправки сообщений с помощью Request на примере Send.

**Comment by Frozel** [comment]
А если просто прописывать атачменты медиа файлов где-нить? Я не силён в go к сожалению

**Comment by Cloudwhale** [comment]
Смотрите сообщение выше.

**Comment by Frozel** [comment]
Ну у меня изначально был прописан токен сообщества, а не пользователя. Чтобы при отправке сообщения бот использовал ключ сообщества, а остальные действия токен пользователя, то нужно переписать функцию на го, на что возможности нет..
